config/routes.rb
Rails.application.routes.draw do

  resources :project_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root "project_lists#index"
end

app/models/project_list.rb
class ProjectList < ActiveRecord::Base
  has_many :todo_items

  validates :title, presence: true
  validates :description, presence: true
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :project_list
  validates :content, presence: true

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/project_lists_controller.rb
class ProjectListsController < ApplicationController
  before_action :set_project_list, only: [:show, :edit, :update, :destroy]

  # GET /project_lists
  # GET /project_lists.json
  def index
    @project_lists = ProjectList.all
  end

  # GET /project_lists/1
  # GET /project_lists/1.json
  def show
  end

  # GET /project_lists/new
  def new
    @project_list = ProjectList.new
  end

  # GET /project_lists/1/edit
  def edit
  end

  # POST /project_lists
  # POST /project_lists.json
  def create
    @project_list = ProjectList.new(project_list_params)

    respond_to do |format|
      if @project_list.save
        format.html { redirect_to @project_list, notice: 'Project list was successfully created.' }
        format.json { render :show, status: :created, location: @project_list }
      else
        format.html { render :new }
        format.json { render json: @project_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_lists/1
  # PATCH/PUT /project_lists/1.json
  def update
    respond_to do |format|
      if @project_list.update(project_list_params)
        format.html { redirect_to @project_list, notice: 'Project list was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_list }
      else
        format.html { render :edit }
        format.json { render json: @project_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_lists/1
  # DELETE /project_lists/1.json
  def destroy
    @project_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_list
      @project_list = ProjectList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_list_params
      params.require(:project_list).permit(:title, :description)
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_project_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @project_list.todo_items.create(todo_item_params)
    redirect_to @project_list
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "Item was deleted."
    else
      flash[:error] = "Item could not be deleted."
    end
    redirect_to @project_list
  end

  def complete
    if @todo_item.completed_at.blank?
      @todo_item.update_attribute(:completed_at, Time.now)
      redirect_to @project_list, notice: "Todo item completed."
    else
      @todo_item.update_attribute(:completed_at, nil)
      redirect_to @project_list, notice: "Todo item marked as not completed."
    end
  end



  private

  def set_todo_item
    @todo_item = @project_list.todo_items.find(params[:id])
  end

  def set_project_list
    @project_list = ProjectList.find(params[:project_list_id])
  end

  def todo_item_params
   params[:todo_item].permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_lists_helper.rb
module ProjectListsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testtask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/project_lists/_form.html.erb
<%= form_for(@project_list) do |f| %>
  <% if @project_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_list.errors.count, "error") %> prohibited this project_list from being saved:</h2>

      <ul>
      <% @project_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_lists/create.js.erb
$('#project_lists').html("<%= j (render @project_list) %>");
$('#task-form').slideUp(350);

app/views/project_lists/edit.html.erb
<h1 class="todo_list_title">Edit Project</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', project_lists_path %>
</div>

app/views/project_lists/index.html.erb
<div class="links">
  <%= link_to "New Project", new_project_list_path %>
</div>
<% @project_lists.each do |project_list| %>
  <div class=index_row clearfix">
    <h2 class="todo_list_title"><%= link_to project_list.title, project_list %></h2>
    <p class="todo_list_sub_title"><%= project_list.description %></p>
  </div>
<% end %>

app/views/project_lists/new.html.erb
<h1 class="todo_list_title">New Project</h1>


<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Back', project_lists_path %>
</div>

app/views/project_lists/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/project_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @project_list.title %></h2>
<p class="todo_list_sub_title"><%= @project_list.description %></p>

<div id="todo_items_wrapper">
  <%= render @project_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_project_list_path(@project_list) %> |
  <%= link_to 'Delete', project_list_path(@project_list), method: :delete, data: {confirm: "Are you sure?" } %> |
  <%= link_to 'Back', project_lists_path %>
</div>

app/views/todo_items/_form.html.erb
<%= form_for([@project_list, @project_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New ToDo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <% if todo_item.completed? %>
    <div class="complete">
      <%= link_to complete_project_list_todo_item_path(@project_list, todo_item.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_project_list_todo_item_path(@project_list, todo_item.id), method: :patch do %>
        <i class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p><%= todo_item.content %></p>
    </div>
  <% end %>
    <div class="trash">
      <%= link_to project_list_todo_item_path(@project_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash"></i>
    <% end %>
    </div>
</div>